namespace DXF.Blocks {
    /**
     * Block-type flags (bit-coded values, may be combined).
     */
    export enum BlockTypeFlags {
        /**
         * Indicates none of the following flags apply.
         */
        None = 0,

        /**
         * This is an anonymous block generated by hatching, associative dimensioning, other internal operations, or an application.
         */
        AnonymousBlock = 1,

        /**
         * This block has non-constant attribute definitions
         * (this bit is not set if the block has any attribute definitions that are constant, or has no attribute definitions at all).
         */
        NonConstantAttributeDefinitions = 2,

        /**
         * This block is an external reference.
         */
        XRef = 4,

        /**
         * This block is an external reference overlay.
         */
        XRefOverlay = 8,

        /**
         * This block is externally dependent.
         */
        ExternallyDependent = 16,

        /**
         * This is a resolved external reference, or dependent of an external reference (ignored on input).
         */
        ResolvedExternalReference = 32,

        /**
         * This definition is a referenced external reference (ignored on input).
         */
        DefinitionExternalReference = 64
    }
}
